# File Integrity Monitoring Policy
# Tracks changes to critical system files and directories

apiVersion: security.qualys.com/v1
kind: TracingPolicy
metadata:
  name: file-integrity-monitoring

spec:
  fileIntegrityMonitoring:
    enabled: true
    paths:
      # System configuration
      - path: /etc/passwd
        events: [open, write]
        severity: critical
        action: alert

      - path: /etc/shadow
        events: [open, write]
        severity: critical
        action: alert

      - path: /etc/group
        events: [open, write]
        severity: high
        action: alert

      # SSH keys
      - path: /root/.ssh
        recursive: true
        events: [open, write, unlink, chmod]
        severity: critical
        action: alert

      - path: /home/*/.ssh/authorized_keys
        events: [open, write, unlink]
        severity: critical
        action: alert

      # Cron jobs (persistence)
      - path: /etc/cron.d
        recursive: true
        events: [write, unlink]
        severity: high
        action: alert

      - path: /etc/cron.daily
        recursive: true
        events: [write, unlink]
        severity: high
        action: alert

      - path: /var/spool/cron
        recursive: true
        events: [write, unlink]
        severity: high
        action: alert

      # System binaries
      - path: /bin
        events: [write, unlink]
        severity: critical
        action: alert

      - path: /sbin
        events: [write, unlink]
        severity: critical
        action: alert

      - path: /usr/bin
        events: [write, unlink]
        severity: critical
        action: alert

      - path: /usr/sbin
        events: [write, unlink]
        severity: critical
        action: alert

      # Init scripts (persistence)
      - path: /etc/init.d
        recursive: true
        events: [write, unlink]
        severity: high
        action: alert

      - path: /etc/systemd/system
        recursive: true
        events: [write, unlink]
        severity: high
        action: alert

  actions:
    log:
      enabled: true
      destination: cloudwatch

    alert:
      enabled: true
      destinations:
        - type: qualys-crs
          enabled: true

  performance:
    samplingRate: 1.0  # Monitor 100% of FIM events
