AWSTemplateFormatVersion: '2010-09-09'
Description: 'Qualys Fargate Scanner - Centralized Spoke (Member Account)'

Parameters:
  SecurityAccountId:
    Type: String
    Description: 'AWS Account ID of the central security account (hub)'
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be a 12-digit AWS account ID

  CentralEventBusArn:
    Type: String
    Description: 'ARN of the central EventBridge bus in the security account'

  QualysBaseAccountId:
    Type: String
    Description: 'Qualys Base Account ID (required if CreateRole is true)'
    AllowedPattern: '^(\d{12})?$'
    ConstraintDescription: Must be a 12-digit AWS account ID or empty
    Default: ''

  QualysExternalId:
    Type: String
    Description: 'External ID for IAM role trust (required if CreateRole is true)'
    NoEcho: true
    Default: ''

  CreateRole:
    Type: String
    Description: 'Whether to create a new IAM role for Qualys ECR access (set to false to use existing role)'
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  ExistingRoleName:
    Type: String
    Description: 'Name of existing IAM role for Qualys ECR access (required if CreateRole is false)'
    Default: ''

Conditions:
  ShouldCreateRole: !Equals [!Ref CreateRole, 'true']

Resources:
  # ==================== IAM Role for Qualys ECR Access ====================
  QualysECRRole:
    Type: AWS::IAM::Role
    Condition: ShouldCreateRole
    Properties:
      RoleName: 'qualys-fargate-scan-role'
      Description: 'Role assumed by Qualys Registry Sensor to pull images from ECR'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${QualysBaseAccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref QualysExternalId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  # ==================== EventBridge Forwarding ====================
  ForwardEventsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PutEventsToHub
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource: !Ref CentralEventBusArn

  # Forward ECS events to central hub
  ForwardECSEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'qualys-fargate-scanner-forward'
      Description: 'Forward ECS events to central security account'
      EventPattern:
        source: [aws.ecs]
        detail-type: [AWS API Call via CloudTrail]
        detail:
          eventSource: [ecs.amazonaws.com]
          eventName:
            - RegisterTaskDefinition
            - RunTask
            - CreateService
            - UpdateService
      Targets:
        - Arn: !Ref CentralEventBusArn
          Id: ForwardToHub
          RoleArn: !GetAtt ForwardEventsRole.Arn

  # ==================== CloudTrail ====================
  TrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'qualys-fargate-trail-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: Expire
            Status: Enabled
            ExpirationInDays: 7

  TrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt TrailBucket.Arn
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${TrailBucket.Arn}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  ECSTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: TrailBucketPolicy
    Properties:
      TrailName: 'qualys-fargate-scanner-trail'
      S3BucketName: !Ref TrailBucket
      IsLogging: true
      IncludeGlobalServiceEvents: false
      IsMultiRegionTrail: false
      EventSelectors:
        - ReadWriteType: WriteOnly
          IncludeManagementEvents: true

Outputs:
  ECRRoleArn:
    Value: !If
      - ShouldCreateRole
      - !GetAtt QualysECRRole.Arn
      - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ExistingRoleName}'
    Description: 'IAM role ARN for Qualys ECR access in this account'

  ECRRoleName:
    Value: !If
      - ShouldCreateRole
      - 'qualys-fargate-scan-role'
      - !Ref ExistingRoleName
    Description: 'IAM role name for Qualys ECR access'

  AccountId:
    Value: !Ref AWS::AccountId
    Description: 'This account ID'
