AWSTemplateFormatVersion: '2010-09-09'
Description: 'Qualys Fargate Scanner - Service Account (Hub)'

Parameters:
  QualysGatewayUrl:
    Type: String
    Description: Qualys Gateway URL for your POD
    Default: 'https://gateway.qg2.apps.qualys.com'
    AllowedValues:
      - 'https://gateway.qg1.apps.qualys.com'
      - 'https://gateway.qg2.apps.qualys.com'
      - 'https://gateway.qg3.apps.qualys.com'
      - 'https://gateway.qg4.apps.qualys.com'
      - 'https://gateway.qg1.apps.qualys.eu'
      - 'https://gateway.qg2.apps.qualys.eu'
      - 'https://gateway.qg1.apps.qualys.in'
      - 'https://gateway.qg1.apps.qualys.ca'
      - 'https://gateway.qg1.apps.qualys.ae'
      - 'https://gateway.qg1.apps.qualys.co.uk'
      - 'https://gateway.qg1.apps.qualys.com.au'

  QualysApiToken:
    Type: String
    Description: Qualys API Bearer Token
    NoEcho: true

  OrganizationId:
    Type: String
    Description: 'AWS Organization ID (e.g., o-xxxxxxxxxx) - allows all org accounts to send events'
    Default: ''

  TargetAccountIds:
    Type: CommaDelimitedList
    Description: 'Comma-separated list of target account IDs (alternative to OrganizationId, include this account for single-account deployment)'
    Default: ''

  ECRRoleName:
    Type: String
    Description: 'Name of IAM role in target accounts for Qualys ECR access'
    Default: 'qualys-fargate-scan-role'

  NotificationEmail:
    Type: String
    Description: Email for scan notifications (optional)
    Default: ''

  MaxPollAttempts:
    Type: Number
    Description: Max times to poll for scan completion
    Default: 30
    MinValue: 5
    MaxValue: 60

  PollIntervalSeconds:
    Type: Number
    Description: Seconds between poll attempts
    Default: 60
    MinValue: 30
    MaxValue: 300

  LambdaReservedConcurrency:
    Type: Number
    Description: 'Reserved concurrent executions for Lambda (0 = no limit)'
    Default: 10
    MinValue: 0
    MaxValue: 100

  Environment:
    Type: String
    Description: 'Environment tag for resources'
    Default: 'production'
    AllowedValues:
      - 'production'
      - 'staging'
      - 'development'

Conditions:
  HasEmail: !Not [!Equals [!Ref NotificationEmail, '']]
  HasOrgId: !Not [!Equals [!Ref OrganizationId, '']]
  HasTargetAccounts: !Not [!Equals [!Join ['', !Ref TargetAccountIds], '']]
  HasReservedConcurrency: !Not [!Equals [!Ref LambdaReservedConcurrency, 0]]

Resources:
  # ==================== KMS Key for Encryption ====================
  EncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub 'KMS key for ${AWS::StackName} encryption'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow SNS
            Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action:
              - kms:GenerateDataKey*
              - kms:Decrypt
            Resource: '*'
          - Sid: Allow CloudWatch Logs
            Effect: Allow
            Principal:
              Service: !Sub 'logs.${AWS::Region}.amazonaws.com'
            Action:
              - kms:Encrypt*
              - kms:Decrypt*
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:Describe*
            Resource: '*'
            Condition:
              ArnLike:
                kms:EncryptionContext:aws:logs:arn: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-*'
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Environment
          Value: !Ref Environment

  EncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${AWS::StackName}-key'
      TargetKeyId: !Ref EncryptionKey

  # ==================== Central EventBridge Bus ====================
  CentralEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub '${AWS::StackName}-bus'

  CentralEventBusPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Ref CentralEventBus
      StatementId: AllowTargetAccounts
      Statement:
        Effect: Allow
        Principal: '*'
        Action: events:PutEvents
        Resource: !GetAtt CentralEventBus.Arn
        Condition:
          StringEquals:
            !If
              - HasOrgId
              - aws:PrincipalOrgID: !Ref OrganizationId
              - aws:PrincipalAccount: !Ref TargetAccountIds

  # ==================== Secrets ====================
  QualysSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AWS::StackName}-qualys-creds'
      Description: 'Qualys API credentials for container scanning'
      KmsKeyId: !Ref EncryptionKey
      SecretString: !Sub '{"qualys_token":"${QualysApiToken}","qualys_gateway_url":"${QualysGatewayUrl}"}'
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Environment
          Value: !Ref Environment

  # ==================== DynamoDB ====================
  ScanCache:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub '${AWS::StackName}-cache'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: imageDigest
          AttributeType: S
      KeySchema:
        - AttributeName: imageDigest
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !Ref EncryptionKey
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      DeletionProtectionEnabled: true
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Environment
          Value: !Ref Environment

  # ==================== SNS ====================
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-notifications'
      KmsMasterKeyId: !Ref EncryptionKey
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Environment
          Value: !Ref Environment

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasEmail
    Properties:
      Protocol: email
      TopicArn: !Ref NotificationTopic
      Endpoint: !Ref NotificationEmail

  # ==================== CloudWatch Logs ====================
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-scanner'
      RetentionInDays: 30
      KmsKeyId: !GetAtt EncryptionKey.Arn
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Environment
          Value: !Ref Environment

  # ==================== Lambda ====================
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ScannerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: SecretsManagerAccess
                Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref QualysSecret
              - Sid: KMSDecrypt
                Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !GetAtt EncryptionKey.Arn
              - Sid: DynamoDBAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                Resource: !GetAtt ScanCache.Arn
              - Sid: SNSPublish
                Effect: Allow
                Action: sns:Publish
                Resource: !Ref NotificationTopic
              - Sid: ECSDescribeTaskDefinition
                Effect: Allow
                Action: ecs:DescribeTaskDefinition
                Resource: '*'
              - Sid: STSGetCallerIdentity
                Effect: Allow
                Action: sts:GetCallerIdentity
                Resource: '*'
              - Sid: XRayTracing
                Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: '*'
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Environment
          Value: !Ref Environment

  ScannerLambda:
    Type: AWS::Lambda::Function
    DependsOn: LambdaLogGroup
    Properties:
      FunctionName: !Sub '${AWS::StackName}-scanner'
      Runtime: python3.11
      Handler: handlers.dispatch
      Role: !GetAtt LambdaRole.Arn
      Timeout: 60
      MemorySize: 256
      ReservedConcurrentExecutions: !If
        - HasReservedConcurrency
        - !Ref LambdaReservedConcurrency
        - !Ref AWS::NoValue
      TracingConfig:
        Mode: Active
      Code:
        ZipFile: |
          def dispatch(event, context):
              return {"status": "placeholder"}
      Environment:
        Variables:
          QUALYS_SECRET_ARN: !Ref QualysSecret
          CACHE_TABLE_NAME: !Ref ScanCache
          SNS_TOPIC_ARN: !Ref NotificationTopic
          API_TIMEOUT_SECONDS: '30'
          ECR_ROLE_NAME: !Ref ECRRoleName
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Environment
          Value: !Ref Environment

  # ==================== Step Functions ====================
  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt ScannerLambda.Arn
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Environment
          Value: !Ref Environment

  ScanWorkflow:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub '${AWS::StackName}-workflow'
      RoleArn: !GetAtt StepFunctionRole.Arn
      TracingConfiguration:
        Enabled: true
      Definition:
        Comment: Qualys Fargate/ECS Image Scan Workflow
        StartAt: ParseEvent
        States:
          ParseEvent:
            Type: Task
            Resource: !GetAtt ScannerLambda.Arn
            Parameters:
              action: parse_event
              input.$: $
            ResultPath: $
            Retry:
              - ErrorEquals: [States.TaskFailed]
                IntervalSeconds: 5
                MaxAttempts: 3
                BackoffRate: 2
            Next: HasImages

          HasImages:
            Type: Choice
            Choices:
              - Variable: $.has_images
                BooleanEquals: false
                Next: NoImages
            Default: CheckCache

          NoImages:
            Type: Succeed
            Comment: No ECR images found in event

          CheckCache:
            Type: Task
            Resource: !GetAtt ScannerLambda.Arn
            Parameters:
              action: check_cache
              input.$: $
            ResultPath: $
            Retry:
              - ErrorEquals: [States.TaskFailed]
                IntervalSeconds: 5
                MaxAttempts: 3
                BackoffRate: 2
            Next: IsCached

          IsCached:
            Type: Choice
            Choices:
              - Variable: $.cached
                BooleanEquals: true
                Next: SkipScan
            Default: GetRegistry

          SkipScan:
            Type: Succeed
            Comment: Image already scanned recently

          GetRegistry:
            Type: Task
            Resource: !GetAtt ScannerLambda.Arn
            Parameters:
              action: get_registry
              input.$: $
            ResultPath: $
            Retry:
              - ErrorEquals: [States.TaskFailed]
                IntervalSeconds: 10
                MaxAttempts: 3
                BackoffRate: 2
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: ScanFailed
            Next: SubmitScan

          SubmitScan:
            Type: Task
            Resource: !GetAtt ScannerLambda.Arn
            Parameters:
              action: submit_scan
              input.$: $
            ResultPath: $
            Retry:
              - ErrorEquals: [States.TaskFailed]
                IntervalSeconds: 10
                MaxAttempts: 3
                BackoffRate: 2
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: ScanFailed
            Next: InitPollCount

          InitPollCount:
            Type: Pass
            Result: 0
            ResultPath: $.poll_count
            Next: WaitForScan

          WaitForScan:
            Type: Wait
            SecondsPath: $.wait_seconds
            Next: CheckStatus

          CheckStatus:
            Type: Task
            Resource: !GetAtt ScannerLambda.Arn
            Parameters:
              action: check_status
              input.$: $
            ResultPath: $
            Retry:
              - ErrorEquals: [States.TaskFailed]
                IntervalSeconds: 10
                MaxAttempts: 2
            Next: EvaluateStatus

          EvaluateStatus:
            Type: Choice
            Choices:
              - Variable: $.scan_complete
                BooleanEquals: true
                Next: GetResults
              - Variable: $.poll_count
                NumericGreaterThanEqualsPath: $.max_polls
                Next: ScanTimeout
            Default: IncrementPoll

          IncrementPoll:
            Type: Pass
            Parameters:
              repository.$: $.repository
              digest.$: $.digest
              tag.$: $.tag
              registry_uuid.$: $.registry_uuid
              poll_count.$: States.MathAdd($.poll_count, 1)
              max_polls.$: $.max_polls
              wait_seconds.$: $.wait_seconds
              account_id.$: $.account_id
              region.$: $.region
            Next: WaitForScan

          ScanTimeout:
            Type: Pass
            Result:
              status: timeout
            ResultPath: $.result
            Next: SendNotification

          GetResults:
            Type: Task
            Resource: !GetAtt ScannerLambda.Arn
            Parameters:
              action: get_results
              input.$: $
            ResultPath: $
            Retry:
              - ErrorEquals: [States.TaskFailed]
                IntervalSeconds: 10
                MaxAttempts: 3
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: ScanFailed
            Next: SendNotification

          SendNotification:
            Type: Task
            Resource: !GetAtt ScannerLambda.Arn
            Parameters:
              action: notify
              input.$: $
            End: true

          ScanFailed:
            Type: Task
            Resource: !GetAtt ScannerLambda.Arn
            Parameters:
              action: notify_failure
              input.$: $
            End: true
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Environment
          Value: !Ref Environment

  # ==================== EventBridge Rules ====================
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartWorkflow
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: states:StartExecution
                Resource: !Ref ScanWorkflow
      Tags:
        - Key: Application
          Value: !Ref AWS::StackName
        - Key: Environment
          Value: !Ref Environment

  CentralBusRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AWS::StackName}-trigger'
      EventBusName: !Ref CentralEventBus
      EventPattern:
        source: [aws.ecs]
        detail-type: [AWS API Call via CloudTrail]
        detail:
          eventSource: [ecs.amazonaws.com]
          eventName:
            - RegisterTaskDefinition
            - RunTask
            - CreateService
            - UpdateService
      Targets:
        - Arn: !Ref ScanWorkflow
          Id: ProcessEvent
          RoleArn: !GetAtt EventBridgeRole.Arn
          InputTransformer:
            InputPathsMap:
              eventName: $.detail.eventName
              taskDefArn: $.detail.responseElements.taskDefinition.taskDefinitionArn
              taskDefArnReq: $.detail.requestParameters.taskDefinition
              containers: $.detail.responseElements.taskDefinition.containerDefinitions
              cluster: $.detail.requestParameters.cluster
              serviceName: $.detail.requestParameters.serviceName
              account: $.account
              region: $.region
            InputTemplate: !Sub |
              {
                "trigger_type": <eventName>,
                "task_definition_arn": <taskDefArn>,
                "task_definition_arn_req": <taskDefArnReq>,
                "containers": <containers>,
                "cluster": <cluster>,
                "service_name": <serviceName>,
                "account_id": <account>,
                "region": <region>,
                "max_polls": ${MaxPollAttempts},
                "wait_seconds": ${PollIntervalSeconds}
              }

Outputs:
  CentralEventBusArn:
    Value: !GetAtt CentralEventBus.Arn
    Description: Central EventBridge bus ARN (for target account configuration)
    Export:
      Name: !Sub '${AWS::StackName}-bus-arn'

  CentralEventBusName:
    Value: !Ref CentralEventBus
    Description: Central EventBridge bus name

  ServiceAccountId:
    Value: !Ref AWS::AccountId
    Description: Service account ID (for target account configuration)

  WorkflowArn:
    Value: !Ref ScanWorkflow
    Description: Step Functions workflow ARN

  WorkflowConsole:
    Value: !Sub 'https://${AWS::Region}.console.aws.amazon.com/states/home#/statemachines/view/${ScanWorkflow}'
    Description: Step Functions console URL

  LambdaArn:
    Value: !GetAtt ScannerLambda.Arn
    Description: Scanner Lambda ARN

  SNSTopic:
    Value: !Ref NotificationTopic
    Description: SNS topic for notifications

  EncryptionKeyArn:
    Value: !GetAtt EncryptionKey.Arn
    Description: KMS key ARN for encryption
