AWSTemplateFormatVersion: '2010-09-09'
Description: 'Qualys Fargate Scanner - Target Account (Spoke)'

Parameters:
  ServiceAccountId:
    Type: String
    Description: 'AWS Account ID of the service account (hub)'
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be a 12-digit AWS account ID

  CentralEventBusArn:
    Type: String
    Description: 'ARN of the central EventBridge bus in the service account'

  QualysBaseAccountId:
    Type: String
    Description: 'Qualys Base Account ID (required if CreateRole is true)'
    AllowedPattern: '^(\d{12})?$'
    ConstraintDescription: Must be a 12-digit AWS account ID or empty
    Default: ''

  QualysExternalId:
    Type: String
    Description: 'External ID for IAM role trust (required if CreateRole is true)'
    NoEcho: true
    Default: ''

  CreateRole:
    Type: String
    Description: 'Whether to create a new IAM role for Qualys ECR access'
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  ExistingRoleName:
    Type: String
    Description: 'Name of existing IAM role for Qualys ECR access (required if CreateRole is false)'
    Default: ''

  ECRRoleName:
    Type: String
    Description: 'Name for the IAM role (used when CreateRole is true)'
    Default: 'qualys-fargate-scan-role'

  CreateCloudTrail:
    Type: String
    Description: 'Create CloudTrail in this account/region (set to false if org-level trail exists)'
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'

  Environment:
    Type: String
    Description: 'Environment tag for resources'
    Default: 'production'
    AllowedValues:
      - 'production'
      - 'staging'
      - 'development'

Conditions:
  ShouldCreateRole: !Equals [!Ref CreateRole, 'true']
  ShouldCreateTrail: !Equals [!Ref CreateCloudTrail, 'true']

Resources:
  # ==================== KMS Key for Encryption ====================
  EncryptionKey:
    Type: AWS::KMS::Key
    Condition: ShouldCreateTrail
    Properties:
      Description: !Sub 'KMS key for qualys-fargate-target encryption'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow CloudTrail
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action:
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
            Condition:
              StringLike:
                kms:EncryptionContext:aws:cloudtrail:arn: !Sub 'arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/*'
      Tags:
        - Key: Application
          Value: qualys-fargate-target
        - Key: Environment
          Value: !Ref Environment

  EncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Condition: ShouldCreateTrail
    Properties:
      AliasName: !Sub 'alias/qualys-fargate-target-${AWS::Region}'
      TargetKeyId: !Ref EncryptionKey

  # ==================== IAM Role for Qualys ECR Access ====================
  QualysECRRole:
    Type: AWS::IAM::Role
    Condition: ShouldCreateRole
    Properties:
      RoleName: !Ref ECRRoleName
      Description: 'Role assumed by Qualys Registry Sensor to pull images from ECR'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${QualysBaseAccountId}:root'
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref QualysExternalId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
        - Key: Application
          Value: qualys-fargate-target
        - Key: Environment
          Value: !Ref Environment

  # ==================== EventBridge Forwarding ====================
  ForwardEventsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PutEventsToServiceAccount
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource: !Ref CentralEventBusArn
      Tags:
        - Key: Application
          Value: qualys-fargate-target
        - Key: Environment
          Value: !Ref Environment

  ForwardECSEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: 'qualys-fargate-forward'
      Description: 'Forward ECS events to service account'
      EventPattern:
        source: [aws.ecs]
        detail-type: [AWS API Call via CloudTrail]
        detail:
          eventSource: [ecs.amazonaws.com]
          eventName:
            - RegisterTaskDefinition
            - RunTask
            - CreateService
            - UpdateService
      Targets:
        - Arn: !Ref CentralEventBusArn
          Id: ForwardToServiceAccount
          RoleArn: !GetAtt ForwardEventsRole.Arn

  # ==================== CloudTrail (Optional) ====================
  AccessLogsBucket:
    Type: AWS::S3::Bucket
    Condition: ShouldCreateTrail
    Properties:
      BucketName: !Sub 'qualys-fargate-access-logs-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: ExpireAccessLogs
            Status: Enabled
            ExpirationInDays: 90
      Tags:
        - Key: Application
          Value: qualys-fargate-target
        - Key: Environment
          Value: !Ref Environment

  AccessLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: ShouldCreateTrail
    Properties:
      Bucket: !Ref AccessLogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3ServerAccessLogsPolicy
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${AccessLogsBucket.Arn}/*'
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:s3:::qualys-fargate-trail-${AWS::AccountId}-${AWS::Region}'
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !GetAtt AccessLogsBucket.Arn
              - !Sub '${AccessLogsBucket.Arn}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  TrailBucket:
    Type: AWS::S3::Bucket
    Condition: ShouldCreateTrail
    DependsOn: AccessLogsBucketPolicy
    Properties:
      BucketName: !Sub 'qualys-fargate-trail-${AWS::AccountId}-${AWS::Region}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref EncryptionKey
            BucketKeyEnabled: true
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogsBucket
        LogFilePrefix: trail-bucket-logs/
      LifecycleConfiguration:
        Rules:
          - Id: Expire
            Status: Enabled
            ExpirationInDays: 7
          - Id: NoncurrentVersionExpiration
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30
      Tags:
        - Key: Application
          Value: qualys-fargate-target
        - Key: Environment
          Value: !Ref Environment

  TrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: ShouldCreateTrail
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt TrailBucket.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/qualys-fargate-trail'
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub '${TrailBucket.Arn}/AWSLogs/${AWS::AccountId}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
              ArnLike:
                aws:SourceArn: !Sub 'arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/qualys-fargate-trail'
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !GetAtt TrailBucket.Arn
              - !Sub '${TrailBucket.Arn}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  ECSTrail:
    Type: AWS::CloudTrail::Trail
    Condition: ShouldCreateTrail
    DependsOn: TrailBucketPolicy
    Properties:
      TrailName: 'qualys-fargate-trail'
      S3BucketName: !Ref TrailBucket
      IsLogging: true
      IncludeGlobalServiceEvents: false
      IsMultiRegionTrail: false
      EnableLogFileValidation: true
      KMSKeyId: !Ref EncryptionKey
      EventSelectors:
        - ReadWriteType: WriteOnly
          IncludeManagementEvents: true
      Tags:
        - Key: Application
          Value: qualys-fargate-target
        - Key: Environment
          Value: !Ref Environment

Outputs:
  ECRRoleArn:
    Value: !If
      - ShouldCreateRole
      - !GetAtt QualysECRRole.Arn
      - !Sub 'arn:aws:iam::${AWS::AccountId}:role/${ExistingRoleName}'
    Description: 'IAM role ARN for Qualys ECR access in this account'

  ECRRoleName:
    Value: !If
      - ShouldCreateRole
      - !Ref ECRRoleName
      - !Ref ExistingRoleName
    Description: 'IAM role name for Qualys ECR access'

  AccountId:
    Value: !Ref AWS::AccountId
    Description: 'This account ID'

  Region:
    Value: !Ref AWS::Region
    Description: 'Region where this target stack is deployed'

  EncryptionKeyArn:
    Condition: ShouldCreateTrail
    Value: !GetAtt EncryptionKey.Arn
    Description: KMS key ARN for encryption
